orbs:
  architect: giantswarm/architect@0.4.5
version: 2.1

jobs:
  build:
    machine: true
    steps:
    - checkout

    - run:
        name: Get architect binary
        command: |
          wget -q $(curl -sS -H "Authorization: token $RELEASE_TOKEN" https://api.github.com/repos/giantswarm/architect/releases/tags/v1.0.0 | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
          chmod +x ./architect
          ./architect version

    - run: ./architect build

    - store_test_results:
        path: /tmp/results

    - persist_to_workspace:
        root: .
        paths:
        - ./k8s-setup-network-environment
        - ./architect

  deploy:
    machine: true
    steps:
    - checkout

    - attach_workspace:
        at: .

    - run: ./architect deploy

workflows:
  build:
    jobs:
      - build
      - architect/push-to-docker-legacy:
          name: push-k8s-setup-network-environment-to-aliyun-master
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/k8s-setup-network-environment"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
          - push-k8s-setup-network-environment-to-aliyun-master
